#!/usr/bin/env node
// Generates a mid-size WebP derivative for every full-size scanned page, so the
// full-size viewer doesn't always have to load the ~700-730KB original.
// Naming: "1989-01-01.jpg" -> "1989-01-01_m.webp", written next to the original.
//
// These derivatives are build output, not source: they're gitignored and
// regenerated by `yarn build` (locally and in CI) from the committed originals.
// Existing files are left alone, so a rebuild costs nothing once they exist.
//
// Run: node scripts/generateResponsiveImages.js [--limit N] [--force]
import { readFileSync, existsSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import sharp from 'sharp';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FILE_LIST_PATH = path.join(__dirname, '..', 'src', 'fileList.json');
const PUBLIC_DIR = path.join(__dirname, '..', 'public');

const TARGET_WIDTH = 960;
const WEBP_QUALITY = 80;

const limitArg = process.argv.find((a) => a.startsWith('--limit'));
const limit = limitArg ? parseInt(limitArg.split('=')[1] ?? process.argv[process.argv.indexOf(limitArg) + 1], 10) : Infinity;
const force = process.argv.includes('--force');

const fileList = JSON.parse(readFileSync(FILE_LIST_PATH, 'utf-8'));

const originals = [];
for (const yearContent of Object.values(fileList)) {
  for (const images of Object.values(yearContent)) {
    for (const entry of images) {
      if (entry.image) {
        originals.push(entry.image);
      }
    }
  }
}

const toDerivativePath = (imagePath) => imagePath.replace(/\.jpe?g$/i, '_m.webp');

let processed = 0;
let skipped = 0;
let upToDate = 0;
let failed = 0;
let totalOriginalBytes = 0;
let totalDerivativeBytes = 0;

const targets = originals.slice(0, limit);
console.log(`Processing ${targets.length} of ${originals.length} originals (target width ${TARGET_WIDTH}px, quality ${WEBP_QUALITY})...`);

for (const imagePath of targets) {
  const srcPath = path.join(PUBLIC_DIR, imagePath);
  const destPath = path.join(PUBLIC_DIR, toDerivativePath(imagePath));

  if (!existsSync(srcPath)) {
    console.warn(`Missing source, skipping: ${srcPath}`);
    skipped++;
    continue;
  }

  if (!force && existsSync(destPath)) {
    upToDate++;
    continue;
  }

  try {
    const srcStat = readFileSync(srcPath);
    totalOriginalBytes += srcStat.length;

    await sharp(srcStat)
      .resize({ width: TARGET_WIDTH, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY })
      .toFile(destPath);

    const destStat = readFileSync(destPath);
    totalDerivativeBytes += destStat.length;
    processed++;

    if (processed % 50 === 0) {
      console.log(`  ${processed}/${targets.length} done...`);
    }
  } catch (err) {
    // existsSync at the top of the loop is the only freshness test there is, so
    // ANY dest file still on disk after a failure — a --force run that threw
    // over an existing rendition, a partial write, one left by an interrupted
    // run — is counted as up to date by the next run: failed is 0, the gate at
    // the bottom passes, and the build ships the corrupt file. (Measured: a
    // 21-byte junk .webp survives a throw and is picked up as "already
    // present".) Deleting it keeps the failure visible as work still to do.
    rmSync(destPath, { force: true });
    console.error(`Failed on ${imagePath}: ${err.message}`);
    failed++;
  }
}

console.log('---');
console.log(`Processed: ${processed}, already present: ${upToDate}, skipped (missing source): ${skipped}, failed: ${failed}`);
console.log(`Original total: ${(totalOriginalBytes / 1024 / 1024).toFixed(1)} MB`);
console.log(`Derivative total: ${(totalDerivativeBytes / 1024 / 1024).toFixed(1)} MB`);

// This runs inside `yarn build`, so a silent partial failure would ship pages
// whose derivative is missing and go green in CI. Fail the build instead.
if (failed > 0 || skipped > 0) {
    console.error(
        `\nERROR: ${failed} image(s) failed and ${skipped} source(s) were missing. ` +
        `The build would ship scans without their WebP rendition.`
    );
    process.exit(1);
}
